<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/7 0007
 * Time: 10:52
 */
namespace app\api\common;

use app\api\model\User;
use think\Controller;
use think\Request;

class Auth extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $request_header = Request::instance()->header();
        $access_token = $request_header['access-token']; //ctrl+shift+u 大小写切换
        if(!($res = User::checkAuth($access_token))){
            echo json_encode(msg(6001,'access_token无效'));
            exit;
        }
        return true;
    }
}