<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/7 0007
 * Time: 11:08
 */

namespace app\api\controller;


use app\api\common\Auth;
use app\api\model\User;
use think\Db;
use think\Exception;
use think\Request;

class TimeLineBackend extends Auth
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 后台首页数据列表
     */
    public function getTimeLineList()
    {
        try {
            $page_size = input('page_size', 10);
            $data = Db::name('article')
                ->paginate($page_size)
                ->each(function ($item, $key) {
                    $item['date'] = date('Y-m-d H:i:s', $item['date']);
                    return $item;
                });
            return json(msg(0, 'success', $data));
        } catch (Exception $e) {
            return json(msg(1, $e->getMessage()));
        }
    }

    /**
     * 根据id获得一条blog的详情
     * @return \think\response\Json
     */
    public function getTimeLineDetail(Request $request)
    {
        try {
            $params = $request->param();
            $id = $params['id'];
            $data = Db::name('article')->where('id', $id)->find();
            $data['time'] = date('H:i:s', $data['time']);
            $data['date'] = date('Y-m-d', $data['date']);
            return json(msg(0, 'success', $data));
        } catch (Exception $e) {
            return json(msg(1, $e->getMessage()));
        }
    }

    /**
     * 修改文章
     */
    public function setTimeLine(Request $request)
    {
        try {
            $params = $request->param();
            $data = [
                'title' => $params['title'],
                'desc' => $params['desc'],
                'content' => $params['content'],
                'mood' => $params['mood'],
                'author' => $params['author'],
                'address' => $params['address'],
                'weather' => $params['weather'],
                'date' => $params['date'],
            ];
            $data['time'] = strtotime(date("Y-m-d", $params['date']) . " " . $params['time']) - $params['date'];
            if (empty($params['id'])) {
                Db::name('article')->insert($data);
            } else {
                $data['id'] = $params['id'];
                Db::name('article')->update($data);
            }
            return json(msg(0, 'success'));
        } catch (Exception $e) {
            return json(msg(1, $e->getMessage()));
        }
    }

    /**
     * 修改文章状态
     */
    public function delTimeLine(Request $request)
    {
        try {
            $params = $request->param();
            $status = Db::name('article')->where('id', $params['id'])->value('status');
            $data = [
                'id' => $params['id'],
                'status' => $status == 0 ? 1 : 0
            ];
            Db::name('article')->update($data);
            return json(msg(0, 'success'));
        } catch (Exception $e) {
            return json(msg(1, $e->getMessage()));
        }
    }
}